name: test_indexdb
version: 1.0.0+1
description: A Flutter project to test the IndexedDb ObjectStore.
publish_to: 'none' 


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  uuid: ^2.1.0

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  uses-material-design: true
